language: node_js
node_js:
  - '6'
before_install:
  - npm install -g grunt-cli
before_script:
  - git clone https://github.com/ONLYOFFICE/web-apps.git ../web-apps
  - cd build
script:
  - npm install
  - grunt --level=SIMPLE
