language: node_js
node_js:
  - '6'
before_install:
  - npm install -g grunt-cli node-qunit-phantomjs
before_script:
  - git clone -b develop https://github.com/ONLYOFFICE/web-apps.git ../web-apps
script:
  - node-qunit-phantomjs cell/.unit-tests/FormulaTests.html
  - cd build
  - npm install
  - grunt --level=WHITESPACE_ONLY
