sudo: required
services:
  - docker
language: node_js
node_js:
  - '6'
before_script:
  - git clone -b develop https://github.com/ONLYOFFICE/web-apps.git ../web-apps
addons:
  sonarcloud:
    organization: "onlyoffice"
    branches:
          - develop
jobs:
  include:
    - stage: SonarQube Scanner
      script:
        - sonar-scanner
    - stage: Formulas tests
      script:
        - npm install -g node-qunit-phantomjs
        - node-qunit-phantomjs cell/.unit-tests/FormulaTests.html
    - stage: Building SDK and test it by `onlyofficetestingrobot/doc-builder-testing`
      script:
        - npm install -g grunt-cli
        - npm install --prefix build
        - grunt --level=WHITESPACE_ONLY --base build --gruntfile build/Gruntfile.js
        - docker pull onlyofficetestingrobot/doc-builder-testing:develop-latest
        - travis_wait docker run -v $PWD/word:/opt/onlyoffice/documentbuilder/sdkjs/word
                                 -v $PWD/cell:/opt/onlyoffice/documentbuilder/sdkjs/cell
                                 -v $PWD/slide:/opt/onlyoffice/documentbuilder/sdkjs/slide
                                 onlyofficetestingrobot/doc-builder-testing:develop-latest
notifications:
  email:
    recipients:
      - shockwavenn@gmail.com
    on_success: never
    on_failure: always
env:
  global:
    secure: wC+umfjaNW4L0yt9N4nV2gLrLa3ajVbfmEakv4Oou58OWUa5eiMc38+hqVXDe6H7bzS0gvdCnnXso89rKQSzl3FlQ2qGYpPQcIuhTWi0j14AE5tfIYR6XcxGgKKYHYdEQ6HgIKq+gL1tizk340RCLuyqhzr3q4xghnUmoxlv/AAg9hz1jGLIYJ91mjLOAT0rSw67EUxeJk2W7Xk5rN3HxxI6vLmZF0rJjc5kvZhmVdELCq7hHbupyCYPnaB6tWKsI1XqSk5wdXvoTgEegPJ3gF9J5mxOqrC2A1vAtpA6lrcGFBx0Bt98vIHlSMwuESvhzmQlP+7wnknlXUsAjY7WRKiskgD0Y394cS9jgzb7qzTqYRDxQwBW/+sXTHTM0+CyK8Aon1LtFjrkRLiKP7M/3YoVpl3YmDhyDE28fHAGJnkudPmqbYoFsWpZmhRv3KqQj2rR9h1xLGMsJx6YudxuqzTUl8Dr+W51bB0bJzWxxJTnB4UIA0yhuKH+oSE8Fk7v+v+rORmQoaZ1v28J8rLGDMmgnsidaI7UrirbOCaDJdEErP5C3hha3DxfMblwj5MgL4y4HyLF3a381Tvv7oe+Ow8LAAKs18RUpVNMP4rF3izYcu12kFjtgY1yoc5Dkykhk/R00iHgosUf1HwpfY7L+hqPDnsxh09SvDUvVoIxAKY=
