name: 'Send message to telegram'
description: 'Send message to telegram'
inputs:
  token:
    required: true
  chat:
    required: true
  message:
    required: false
    default: |
      Workflow: ${{ github.workflow }}
      Github job: ${{ github.job }}
      Github job status: '❌' - ${{ job.status }}
      Branch: ${{ github.ref_name }}

      See action run logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}
runs:
  using: "composite"
  steps:
    - name: Send message to telegram
      shell: bash
      env:
        MESSAGE: ${{ inputs.message }}
        TELEGRAM_TOKEN: ${{ inputs.token }}
        TELEGRAM_CHAT: ${{ inputs.chat }}
      run: |
        PAYLOAD=$(jq -n \
          --arg chat_id "$TELEGRAM_CHAT" \
          --arg text "$MESSAGE" \
          '{
            chat_id: $chat_id,
            text: $text,
            parse_mode: "Markdown",
            disable_notification: true,
            disable_web_page_preview: true
          }')
        
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD"
